version: '3'
services:
  titanDWS:
    image: titanDWS
    build:
      context: .
      dockerfile: Dockerfile
      args:
              # this is your proxy url... this is my local CNTLM
              HTTPS_PROXY: ${HTTPS_PROXY}
              HTTP_PROXY: ${HTTP_PROXY}
              https_proxy: ${HTTPS_PROXY}
              http_proxy: ${HTTP_PROXY}

